version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
